# Generated by Django 2.1.7 on 2019-03-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='useless_text',
            field=models.CharField(default='something', max_length=200),
        ),
    ]
